# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemimage',
            field=models.FileField(default='/abcd.jpg', upload_to=''),
        ),
    ]
